### ISSUE TITLE
"Automatically opens tabs" is always on.

### ISSUE THREAD

**Issue by uchidaxel** [gauntface/pin-it-extension#526]
Hello and thank you for developing this nice extention.
From the new update (probably from version 4.00 Aug 12th), it always opens tabs when a new window is created.
I am using the latest Brave (1.68.137 Chromium: 127.0.6533.100).

**Comment by gauntface** [comment]
Apologies for that - I just noticed the issue myself this morning. Will rollback the change until I fix it.

**Comment by gauntface** [comment]
I rolled back the version, so 4.0.1 doesn't have the auto-open feature.

I realized the issue and fixed it - should be coming out with 4.0.2.

Thank you so much for raising this issue and sorry for the issues.

**Comment by gauntface** [comment]
4.0.2 re-adds the feature, but this time the setting is respected.
